//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionOra2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdoBejelentes
    {
        public int ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public int JogCimId { get; set; }
    
        public virtual Jogcim Jogcim { get; set; }
    }
}
